<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Tue, 28 Jan 2014 06:36:01 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_global_comments_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['comment'] = array('canEditNoPost','commentQueued','authorwarn','userIgnoredLang','hasauthormemid','hasauthormidclose','commentignored','moderateCheckbox','enableRep','hasQ','canReply','canEdit','canHide','canApprove','canDelete','hasReport','commentinitignored');
$this->_funcHooks['commentHidden'] = array('canEditNoPost','moderateCheckbox','canUnhide','canDelete');
$this->_funcHooks['commentsList'] = array('comments','comments_top','comments_bottom','hasCaptcha','guestName','allow_comments');
$this->_funcHooks['form'] = array('comment_errors','isEditing','guest_captcha');


}

/* -- comment --*/
function comment($r, $parent, $settings) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['comment'] ) )
{
$count_64a1a8eb35a54353fff8affdd4b83b13 = is_array($this->functionData['comment']) ? count($this->functionData['comment']) : 0;
$this->functionData['comment'][$count_64a1a8eb35a54353fff8affdd4b83b13]['r'] = $r;
$this->functionData['comment'][$count_64a1a8eb35a54353fff8affdd4b83b13]['parent'] = $parent;
$this->functionData['comment'][$count_64a1a8eb35a54353fff8affdd4b83b13]['settings'] = $settings;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- commentHidden --*/
function commentHidden($r, $parent, $settings) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['commentHidden'] ) )
{
$count_25c9ef0f199547922184a9fca79af3d2 = is_array($this->functionData['commentHidden']) ? count($this->functionData['commentHidden']) : 0;
$this->functionData['commentHidden'][$count_25c9ef0f199547922184a9fca79af3d2]['r'] = $r;
$this->functionData['commentHidden'][$count_25c9ef0f199547922184a9fca79af3d2]['parent'] = $parent;
$this->functionData['commentHidden'][$count_25c9ef0f199547922184a9fca79af3d2]['settings'] = $settings;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- commentsList --*/
function commentsList($comments, $settings, $pages, $parent, $preReply='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['commentsList'] ) )
{
$count_919c53bf426091617ace3380290b02c4 = is_array($this->functionData['commentsList']) ? count($this->functionData['commentsList']) : 0;
$this->functionData['commentsList'][$count_919c53bf426091617ace3380290b02c4]['comments'] = $comments;
$this->functionData['commentsList'][$count_919c53bf426091617ace3380290b02c4]['settings'] = $settings;
$this->functionData['commentsList'][$count_919c53bf426091617ace3380290b02c4]['pages'] = $pages;
$this->functionData['commentsList'][$count_919c53bf426091617ace3380290b02c4]['parent'] = $parent;
$this->functionData['commentsList'][$count_919c53bf426091617ace3380290b02c4]['preReply'] = $preReply;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- form --*/
function form($comment, $parent, $editor="", $settings, $errors="", $do='saveEdit') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['form'] ) )
{
$count_d451711974b8f2854a074df5ba6685d7 = is_array($this->functionData['form']) ? count($this->functionData['form']) : 0;
$this->functionData['form'][$count_d451711974b8f2854a074df5ba6685d7]['comment'] = $comment;
$this->functionData['form'][$count_d451711974b8f2854a074df5ba6685d7]['parent'] = $parent;
$this->functionData['form'][$count_d451711974b8f2854a074df5ba6685d7]['editor'] = $editor;
$this->functionData['form'][$count_d451711974b8f2854a074df5ba6685d7]['settings'] = $settings;
$this->functionData['form'][$count_d451711974b8f2854a074df5ba6685d7]['errors'] = $errors;
$this->functionData['form'][$count_d451711974b8f2854a074df5ba6685d7]['do'] = $do;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- getEditJs --*/
function getEditJs() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>