<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Tue, 28 Jan 2014 06:36:01 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_help_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['helpShowSection'] = array('notajax','isajax','notajax');
$this->_funcHooks['helpShowTopics'] = array('helpfiles');


}

/* -- helpShowSection --*/
function helpShowSection($one_text="",$two_text="",$three_text="", $text) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_help', $this->_funcHooks['helpShowSection'] ) )
{
$count_43ad5d5715e441b434864ab3a6020dc2 = is_array($this->functionData['helpShowSection']) ? count($this->functionData['helpShowSection']) : 0;
$this->functionData['helpShowSection'][$count_43ad5d5715e441b434864ab3a6020dc2]['one_text'] = $one_text;
$this->functionData['helpShowSection'][$count_43ad5d5715e441b434864ab3a6020dc2]['two_text'] = $two_text;
$this->functionData['helpShowSection'][$count_43ad5d5715e441b434864ab3a6020dc2]['three_text'] = $three_text;
$this->functionData['helpShowSection'][$count_43ad5d5715e441b434864ab3a6020dc2]['text'] = $text;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- helpShowTopics --*/
function helpShowTopics($one_text="",$two_text="",$three_text="",$rows) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_help', $this->_funcHooks['helpShowTopics'] ) )
{
$count_391fdd1dbca970c7f08d8a64c2455ab0 = is_array($this->functionData['helpShowTopics']) ? count($this->functionData['helpShowTopics']) : 0;
$this->functionData['helpShowTopics'][$count_391fdd1dbca970c7f08d8a64c2455ab0]['one_text'] = $one_text;
$this->functionData['helpShowTopics'][$count_391fdd1dbca970c7f08d8a64c2455ab0]['two_text'] = $two_text;
$this->functionData['helpShowTopics'][$count_391fdd1dbca970c7f08d8a64c2455ab0]['three_text'] = $three_text;
$this->functionData['helpShowTopics'][$count_391fdd1dbca970c7f08d8a64c2455ab0]['rows'] = $rows;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>