<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Tue, 28 Jan 2014 06:36:01 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_forum_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['forumAttachments'] = array('attachments');
$this->_funcHooks['forumIndexTemplate'] = array('announcedates','announcements','showSubForumsLit','isNotLast','subforums','canSeeLastInfoRedirect','hasQueuedAndCanSeeIcon','showSubForums','hideTopicInTitle','lastPosterID','hideDateUrl','hideLastInfo','canSeeLastInfoSubs','forumRedirect','forums','subforumdata','subforums','topics','moderatorpopup','moderatorscomma','moderators','mm','hasFollowData','watchismember','rulesinline','ruleslink','rules','hasannouncements','hassubforums','isGuestPostTopicTop','usercanpost','moderationDropdownLink','markRead','moderationDropdownMenu','topicsismod','ka_last_post','ka_start_date','ka_replies','ka_viewed','ka_viewed','answerLink','answerMenu','topicsismod','canSeeLastInfoHeader','topicsismod','notopicsspan','hastopics','hastopics','isGuestPostTopic','bottomusercanpost','hasmoderators','hasactiveusers','showactiveusers','showtopics','moderationform','hasMultiModeratorOptions','hasUnread','forums','subforums','announcements','topics','usercanpost');
$this->_funcHooks['likeSummaryContents'] = array('likeOnlyMembers');
$this->_funcHooks['topic'] = array('nav','haslastpage','pages','inforumschema','queuedisreadif','inforumelseschema','queuedisreadelse','queuedtopic','hasmodlinks','solvedBadge','archivedBadge','archivingBadge','queuedpostsImg','topicUnapproved','hasPrefix','showForumNav','showReason','topicDeletedReason','hasTags','multipages','canReadPreview','isHot','isMember','replylang','isMemberCloseA','isLink','hasPollBump','canSeeLastInfo','mmtidon','tidRestore','isUnapproved','issupermod','ispinned','islink','closedtopic','opentopic','islink2','topicmoderator','topicIsDeleted','archivedCb','mmicon','adCodeColSpan','adCodeCheck');
$this->_funcHooks['topic_rating_image'] = array('ratinggood','ratings');
$this->_funcHooks['topicPrefixWrap'] = array('prefix');


}

/* -- ajax__deleteTopic --*/
function ajax__deleteTopic() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumAttachments --*/
function forumAttachments($title, $rows, $pages) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['forumAttachments'] ) )
{
$count_95dbffca4199af37fbeba07da11cc1e1 = is_array($this->functionData['forumAttachments']) ? count($this->functionData['forumAttachments']) : 0;
$this->functionData['forumAttachments'][$count_95dbffca4199af37fbeba07da11cc1e1]['title'] = $title;
$this->functionData['forumAttachments'][$count_95dbffca4199af37fbeba07da11cc1e1]['rows'] = $rows;
$this->functionData['forumAttachments'][$count_95dbffca4199af37fbeba07da11cc1e1]['pages'] = $pages;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumIndexTemplate --*/
function forumIndexTemplate($forum_data, $announce_data, $topic_data, $other_data, $multi_mod_data, $sub_forum_data, $footer_filter, $active_user_data, $mod_data, $inforum=1) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['forumIndexTemplate'] ) )
{
$count_44f11633fe7e8453422e79c029fa1823 = is_array($this->functionData['forumIndexTemplate']) ? count($this->functionData['forumIndexTemplate']) : 0;
$this->functionData['forumIndexTemplate'][$count_44f11633fe7e8453422e79c029fa1823]['forum_data'] = $forum_data;
$this->functionData['forumIndexTemplate'][$count_44f11633fe7e8453422e79c029fa1823]['announce_data'] = $announce_data;
$this->functionData['forumIndexTemplate'][$count_44f11633fe7e8453422e79c029fa1823]['topic_data'] = $topic_data;
$this->functionData['forumIndexTemplate'][$count_44f11633fe7e8453422e79c029fa1823]['other_data'] = $other_data;
$this->functionData['forumIndexTemplate'][$count_44f11633fe7e8453422e79c029fa1823]['multi_mod_data'] = $multi_mod_data;
$this->functionData['forumIndexTemplate'][$count_44f11633fe7e8453422e79c029fa1823]['sub_forum_data'] = $sub_forum_data;
$this->functionData['forumIndexTemplate'][$count_44f11633fe7e8453422e79c029fa1823]['footer_filter'] = $footer_filter;
$this->functionData['forumIndexTemplate'][$count_44f11633fe7e8453422e79c029fa1823]['active_user_data'] = $active_user_data;
$this->functionData['forumIndexTemplate'][$count_44f11633fe7e8453422e79c029fa1823]['mod_data'] = $mod_data;
$this->functionData['forumIndexTemplate'][$count_44f11633fe7e8453422e79c029fa1823]['inforum'] = $inforum;
}
$IPBHTML .= "<template>viewForum</template>
<permissions>
	<canPost>{$forum_data['_user_can_post']}</canPost>
	<canPostSoftDelete>{$forum_data['permissions']['PostSoftDelete']}</canPostSoftDelete>
	<canSoftDeleteRestore>{$forum_data['permissions']['PostSoftDeleteRestore']}</canSoftDeleteRestore>
	<canQueue>{$forum_data['permissions']['canQueue']}</canQueue>
</permissions>
<hasActionBar>1</hasActionBar>
<pagination>{$forum_data['SHOW_PAGES']}</pagination>
" . (($forum_data['_user_can_post']) ? ("
<AssessoryButtonURL><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=post&amp;section=post&amp;do=new_post&amp;f={$forum_data['id']}", "publicWithApp",'' ), "", "" ) . "]]></AssessoryButtonURL>
") : ("")) . "
<subforumSubtext>authorName|date</subforumSubtext><!--authorName|date|postTitle-->
<forum>
		
		<title><![CDATA[{$forum_data['name']}]]></title>
		<id>{$forum_data['id']}</id>
		<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "]]></url>
		
" . (($forum_data['show_rules'] == 2) ? ("
		<rules>
			<title><![CDATA[{$forum_data['rules_title']}]]></title>
			<text><![CDATA[{$forum_data['rules_text']}]]></text>
		</rules>
") : ("")) . "
" . (($forum_data['show_rules'] == 1) ? ("
		<rules>
			<title><![CDATA[{$forum_data['rules_title']}]]></title>
			<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}&amp;act=SR", "public",'' ), "", "" ) . "]]></url>
		</rules>
") : ("")) . "
" . ((is_array( $sub_forum_data ) AND count( $sub_forum_data )) ? ("
		<subforums>			
	".$this->__f__7e69451d577e1e73180164a30c5108c3($forum_data,$announce_data,$topic_data,$other_data,$multi_mod_data,$sub_forum_data,$footer_filter,$active_user_data,$mod_data,$inforum)."		</subforums>
") : ("")) . "
" . ((is_array( $announce_data ) AND count( $announce_data )) ? ("
		<announcements>			
	".$this->__f__d245a3e32ad3eddf3b1b811b80a87000($forum_data,$announce_data,$topic_data,$other_data,$multi_mod_data,$sub_forum_data,$footer_filter,$active_user_data,$mod_data,$inforum)."		</announcements>
") : ("")) . "
		<topics>
" . ((is_array( $topic_data ) AND count( $topic_data )) ? ("".$this->__f__de5043877d6b4638b3414597b816ac2c($forum_data,$announce_data,$topic_data,$other_data,$multi_mod_data,$sub_forum_data,$footer_filter,$active_user_data,$mod_data,$inforum)."") : ("")) . "
		</topics>
		
	</forum>";
return $IPBHTML;
}


function __f__4a63c28d368c84c642c5e5d38787cae8($forum_data, $announce_data, $topic_data, $other_data, $multi_mod_data, $sub_forum_data, $footer_filter, $active_user_data, $mod_data, $inforum=1,$_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<forum>
				<id>{$forum_data['id']}</id>
				<title><![CDATA[{$forum_data['name']}]]></title>
				<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "]]></url>
				<description><![CDATA[{$forum_data['description']}]]></description>
					" . (($forum_data['redirect_on']) ? ("							
				<type>redirect</type>
					") : ("<type>{$forum_data['status']}</type>
				<topics>{$forum_data['topics']}</topics>
				<replies>{$forum_data['posts']}</replies>
						" . (($forum_data['_has_unread']) ? ("
							<isRead>0</isRead>
						") : ("
							<isRead>1</isRead>
						")) . "						
				<lastPost>
						" . (($forum_data['hide_last_info']) ? ("
					<name>{$this->lang->words['f_protected']}</name>
						") : ("<date>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($forum_data['last_post'],"DATE", 0)) . "</date>
					<name><![CDATA[{$forum_data['last_title']}]]></name>
					<id>{$forum_data['last_id']}</id>
					<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$forum_data['last_id']}&amp;view=getnewpost", "public",'' ), "{$forum_data['seo_last_title']}", "showtopic" ) . "]]></url>
					<user>
							" . (($forum_data['last_poster_id']) ? ("						
						<id>{$forum_data['last_poster_id']}</id>
						<name><![CDATA[{$forum_data['last_poster_name']}]]></name>
						<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$forum_data['last_poster_id']}", "public",'' ), "{$forum_data['seo_last_name']}", "showuser" ) . "]]></url>										
							") : ("
						<id>0</id>
						<name><![CDATA[{$this->settings['guest_name_pre']}{$forum_data['last_poster_name']}{$this->settings['guest_name_suf']}]]></name>
						<url></url>
							")) . "
					</user>")) . "
				</lastPost>")) . "
			</forum>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__7e69451d577e1e73180164a30c5108c3($forum_data, $announce_data, $topic_data, $other_data, $multi_mod_data, $sub_forum_data, $footer_filter, $active_user_data, $mod_data, $inforum=1)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sub_forum_data as $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("					
			".$this->__f__4a63c28d368c84c642c5e5d38787cae8($forum_data,$announce_data,$topic_data,$other_data,$multi_mod_data,$sub_forum_data,$footer_filter,$active_user_data,$mod_data,$inforum,$_data)."		") : ("")) . "
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__d245a3e32ad3eddf3b1b811b80a87000($forum_data, $announce_data, $topic_data, $other_data, $multi_mod_data, $sub_forum_data, $footer_filter, $active_user_data, $mod_data, $inforum=1)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $announce_data as $aid => $adata )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<announcement>
				<id>{$adata['announce_id']}</id>
				<title><![CDATA[{$adata['announce_title']}]]></title>
				<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showannouncement={$adata['announce_id']}&amp;f={$forum_data['id']}", "public",'' ), "%%{$adata['announce_title']}%%", "showannouncement" ) . "]]></url>
				<user>
					<id>{$adata['member_id']}</id>
					<name><![CDATA[{$adata['member_name']}]]></name>
					<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$adata['member_id']}", "public",'' ), "{$adata['members_seo_name']}", "showuser" ) . "]]></url>
				</user>
			</announcement>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__66e686e62e7dbf2f59e9f593b96613ae($forum_data, $announce_data, $topic_data, $other_data, $multi_mod_data, $sub_forum_data, $footer_filter, $active_user_data, $mod_data, $inforum=1,$tid='',$data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data['pages'] as $page )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<page>					
					<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['tid']}&amp;st={$page['st']}", "public",'' ), "{$data['title_seo']}", "showtopic" ) . "]]></url>
					<number>{$page['page']}</number>
				</page>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__de5043877d6b4638b3414597b816ac2c($forum_data, $announce_data, $topic_data, $other_data, $multi_mod_data, $sub_forum_data, $footer_filter, $active_user_data, $mod_data, $inforum=1)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topic_data as $tid => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<topic>
				<id>{$data['tid']}</id>
				<pinned>{$data['pinned']}</pinned>
				<icon>{$data['folder_img']}</icon>
				<title><![CDATA[{$data['title']}]]></title>
				<description><![CDATA[{$data['description']}]]></description>
				<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['tid']}", "public",'' ), "{$data['title_seo']}", "showtopic" ) . "]]></url>
				<isRead>{$data['folder_img']['is_read']}</isRead>
	
				
				<user>
					<id>{$data['starter_id']}</id>
					<name><![CDATA[{$data['starter_name']}]]></name>
					<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$data['starter_id']}", "public",'' ), "{$data['seo_first_name']}", "showuser" ) . "]]></url>
				</user>
				<replies>{$data['_posts']}</replies>
				<views>{$data['views']}</views>
				<lastPost>
					<date>{$data['last_post']}</date>
					<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['tid']}&amp;view=getnewpost", "public",'' ), "{$data['title_seo']}", "showtopic" ) . "]]></url>
					<user>
						<id>{$data['last_poster_id']}</id>
						<name><![CDATA[{$data['last_poster_name']}]]></name>
						<url><![CDATA[" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$data['last_poster_id']}", "public",'' ), "{$data['seo_last_name']}", "showuser" ) . "]]></url>
					</user>
				</lastPost>
		" . (($data['topic_hasattach']) ? ("
				<attachments>
					<url><![CDATA[{$this->settings['base_url']}app=forums&amp;module=forums&amp;section=attach&amp;tid={$data['tid']}]]></url>
					<count>" . intval($data['topic_hasattach']) . "</count>
				</attachments>
		") : ("")) . "
		" . ((is_array( $data['pages'] ) AND count( $data['pages'] )) ? ("
			<pagination>
			".$this->__f__66e686e62e7dbf2f59e9f593b96613ae($forum_data,$announce_data,$topic_data,$other_data,$multi_mod_data,$sub_forum_data,$footer_filter,$active_user_data,$mod_data,$inforum,$tid,$data)."		</pagination>
		") : ("")) . "		
			</topic>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- forumPasswordLogIn --*/
function forumPasswordLogIn($fid="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeSummary --*/
function likeSummary($data, $relId, $opts) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeSummaryContents --*/
function likeSummaryContents($data, $relId, $opts=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['likeSummaryContents'] ) )
{
$count_61206ad7647bc706fab5518c96dfec4b = is_array($this->functionData['likeSummaryContents']) ? count($this->functionData['likeSummaryContents']) : 0;
$this->functionData['likeSummaryContents'][$count_61206ad7647bc706fab5518c96dfec4b]['data'] = $data;
$this->functionData['likeSummaryContents'][$count_61206ad7647bc706fab5518c96dfec4b]['relId'] = $relId;
$this->functionData['likeSummaryContents'][$count_61206ad7647bc706fab5518c96dfec4b]['opts'] = $opts;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- show_rules --*/
function show_rules($rules="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- topic --*/
function topic($data, $forum_data, $other_data, $inforum) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['topic'] ) )
{
$count_506e07f1a63f5071a14216979d600538 = is_array($this->functionData['topic']) ? count($this->functionData['topic']) : 0;
$this->functionData['topic'][$count_506e07f1a63f5071a14216979d600538]['data'] = $data;
$this->functionData['topic'][$count_506e07f1a63f5071a14216979d600538]['forum_data'] = $forum_data;
$this->functionData['topic'][$count_506e07f1a63f5071a14216979d600538]['other_data'] = $other_data;
$this->functionData['topic'][$count_506e07f1a63f5071a14216979d600538]['inforum'] = $inforum;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- topic_rating_image --*/
function topic_rating_image($rating_id=1) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['topic_rating_image'] ) )
{
$count_4d72a4176b534ebb9a780efcb0063cb5 = is_array($this->functionData['topic_rating_image']) ? count($this->functionData['topic_rating_image']) : 0;
$this->functionData['topic_rating_image'][$count_4d72a4176b534ebb9a780efcb0063cb5]['rating_id'] = $rating_id;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- topicPrefixWrap --*/
function topicPrefixWrap($text) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_forum', $this->_funcHooks['topicPrefixWrap'] ) )
{
$count_188852826b41b6e5b027855a0e5e030f = is_array($this->functionData['topicPrefixWrap']) ? count($this->functionData['topicPrefixWrap']) : 0;
$this->functionData['topicPrefixWrap'][$count_188852826b41b6e5b027855a0e5e030f]['text'] = $text;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>