<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Tue, 28 Jan 2014 06:36:01 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_global_other_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['ajaxPopUpNoPermission'] = array('msg');
$this->_funcHooks['displayBoardOffline'] = array('isGuest');
$this->_funcHooks['displayPopUpWindow'] = array('donotminifycss','cssImport','popupcssInline','popupmetaTags','popupjavascript','popuprss','popuprss','popupraw','popupdocumentHeadItems','popupheaditemtype','minifycss','csstominify','hasimportcss','popupcssinline','popupmetatags','popupminfiyrlhttpsp','popupminfiyrlhttpss','popupminfyjsrl','popupjsmodules','popuphttpsp','popuprl','popupjsmodules','popuphttpss','popuprl2','popupminifyjs','popupdocumenthead','popupbefriend','istm','istl','popupswfupload','popupfurl');
$this->_funcHooks['Error'] = array('haserrorcode','savedpost');
$this->_funcHooks['facebookPop'] = array('hasFbConnected');
$this->_funcHooks['generateTopicIcon'] = array('topicIsMoved','topicIsClosed','topicReadDot','topicUnreadDot','gotolatestwrap');
$this->_funcHooks['globalTemplateMinimal'] = array('fbcenabled','pagenumberintitle','isLargeTouch','isSmallTouch','mainpageContent','lastvisit','isfloat','sqldebuglink','closesqldebuglink','showdebuglevel');
$this->_funcHooks['inboxList'] = array('loopynotify','hasTopics');
$this->_funcHooks['likeMoreDialogue'] = array('hasVisibleEntries','hasAnonEntries');
$this->_funcHooks['likeSummaryContents'] = array('likeOnlyMembers');
$this->_funcHooks['notificationsList'] = array('loopynotify','hasnotifications','notifications');
$this->_funcHooks['questionAndAnswer'] = array('qadefault');
$this->_funcHooks['quickNavigationPanel'] = array('depth','important','innerAgain','hasTitle','linksisarray','outer');
$this->_funcHooks['quickNavigationWrapper'] = array('active','navTabs','isLargeTouch');
$this->_funcHooks['redirectTemplate'] = array('redirectcssImport','redirctcssInline','redirectjs','redirectrss','redirectrsd','redirectraw','redirectdocumentHeadItemsSub','redirectdocumentHeadItems','redirectfull','redirectcssimport','redirectcssinline','redirectdh','redirectmozfull','redirectlink');
$this->_funcHooks['repButtons'] = array('hasNoLikes','giveRepUp','giveRepDown','canGiveRep','pos','giveRepUp','giveRepDown','canGiveRep','hasNoRep','hasPosRep','hasNegRep','isNotLike','isLike','canRep','reputationBox','giveRepUp','canGiveRep','canGiveRep','giveRepDown','isLike','canRep');
$this->_funcHooks['socialSharePostStrip'] = array('canShareThis','services','canSave','canShare');
$this->_funcHooks['tagCloud'] = array('eachTag');
$this->_funcHooks['tagEntry'] = array('noClass','inSearch','inSearchSub','hasSearchSection');
$this->_funcHooks['tagPrefix'] = array('inSearch','inSearchSub','hasSearchSection');
$this->_funcHooks['tagTextEntryBox'] = array('isClosedField','prefixChecked','canPrefix');


}

/* -- ajaxPopUpNoPermission --*/
function ajaxPopUpNoPermission($msg='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['ajaxPopUpNoPermission'] ) )
{
$count_6fbad8dc752cb9e39226f893abd9ca32 = is_array($this->functionData['ajaxPopUpNoPermission']) ? count($this->functionData['ajaxPopUpNoPermission']) : 0;
$this->functionData['ajaxPopUpNoPermission'][$count_6fbad8dc752cb9e39226f893abd9ca32]['msg'] = $msg;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- captchaGD --*/
function captchaGD($captcha_unique_id) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- captchaKeycaptcha --*/
function captchaKeycaptcha($challenge="") {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- captchaRecaptcha --*/
function captchaRecaptcha($html="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- displayBoardOffline --*/
function displayBoardOffline($message="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['displayBoardOffline'] ) )
{
$count_c81081fc5cc1d92aebf8077db4c2cf6a = is_array($this->functionData['displayBoardOffline']) ? count($this->functionData['displayBoardOffline']) : 0;
$this->functionData['displayBoardOffline'][$count_c81081fc5cc1d92aebf8077db4c2cf6a]['message'] = $message;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- displayPopUpWindow --*/
function displayPopUpWindow($documentHeadItems, $css, $jsLoaderItems, $title="", $output="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['displayPopUpWindow'] ) )
{
$count_e71dd7ef9012cf135feda6575681b55a = is_array($this->functionData['displayPopUpWindow']) ? count($this->functionData['displayPopUpWindow']) : 0;
$this->functionData['displayPopUpWindow'][$count_e71dd7ef9012cf135feda6575681b55a]['documentHeadItems'] = $documentHeadItems;
$this->functionData['displayPopUpWindow'][$count_e71dd7ef9012cf135feda6575681b55a]['css'] = $css;
$this->functionData['displayPopUpWindow'][$count_e71dd7ef9012cf135feda6575681b55a]['jsLoaderItems'] = $jsLoaderItems;
$this->functionData['displayPopUpWindow'][$count_e71dd7ef9012cf135feda6575681b55a]['title'] = $title;
$this->functionData['displayPopUpWindow'][$count_e71dd7ef9012cf135feda6575681b55a]['output'] = $output;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- Error --*/
function Error($message="",$code=0,$ad_email_one="",$ad_email_two="", $title="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['Error'] ) )
{
$count_bf9817bd8a3e1d946c0f11fda05df5ff = is_array($this->functionData['Error']) ? count($this->functionData['Error']) : 0;
$this->functionData['Error'][$count_bf9817bd8a3e1d946c0f11fda05df5ff]['message'] = $message;
$this->functionData['Error'][$count_bf9817bd8a3e1d946c0f11fda05df5ff]['code'] = $code;
$this->functionData['Error'][$count_bf9817bd8a3e1d946c0f11fda05df5ff]['ad_email_one'] = $ad_email_one;
$this->functionData['Error'][$count_bf9817bd8a3e1d946c0f11fda05df5ff]['ad_email_two'] = $ad_email_two;
$this->functionData['Error'][$count_bf9817bd8a3e1d946c0f11fda05df5ff]['title'] = $title;
}
$IPBHTML .= "<error>{$message}</error>";
return $IPBHTML;
}

/* -- facebookDone --*/
function facebookDone($user) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- facebookPop --*/
function facebookPop($user=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['facebookPop'] ) )
{
$count_21f110f8a87014ac56ce3e7a488e981e = is_array($this->functionData['facebookPop']) ? count($this->functionData['facebookPop']) : 0;
$this->functionData['facebookPop'][$count_21f110f8a87014ac56ce3e7a488e981e]['user'] = $user;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followUnsubscribe --*/
function followUnsubscribe($data, $meta) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- generateTopicIcon --*/
function generateTopicIcon($imgArray, $unreadUrl) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['generateTopicIcon'] ) )
{
$count_4eafdf7a9be58484d07b57cf027a9d7f = is_array($this->functionData['generateTopicIcon']) ? count($this->functionData['generateTopicIcon']) : 0;
$this->functionData['generateTopicIcon'][$count_4eafdf7a9be58484d07b57cf027a9d7f]['imgArray'] = $imgArray;
$this->functionData['generateTopicIcon'][$count_4eafdf7a9be58484d07b57cf027a9d7f]['unreadUrl'] = $unreadUrl;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- globalTemplateMinimal --*/
function globalTemplateMinimal($html, $documentHeadItems, $css, $jsModules, $metaTags, array $header_items, $items=array(), $footer_items=array(), $stats=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['globalTemplateMinimal'] ) )
{
$count_4a1f80b8c3cca8df3046de6666651ea8 = is_array($this->functionData['globalTemplateMinimal']) ? count($this->functionData['globalTemplateMinimal']) : 0;
$this->functionData['globalTemplateMinimal'][$count_4a1f80b8c3cca8df3046de6666651ea8]['html'] = $html;
$this->functionData['globalTemplateMinimal'][$count_4a1f80b8c3cca8df3046de6666651ea8]['documentHeadItems'] = $documentHeadItems;
$this->functionData['globalTemplateMinimal'][$count_4a1f80b8c3cca8df3046de6666651ea8]['css'] = $css;
$this->functionData['globalTemplateMinimal'][$count_4a1f80b8c3cca8df3046de6666651ea8]['jsModules'] = $jsModules;
$this->functionData['globalTemplateMinimal'][$count_4a1f80b8c3cca8df3046de6666651ea8]['metaTags'] = $metaTags;
$this->functionData['globalTemplateMinimal'][$count_4a1f80b8c3cca8df3046de6666651ea8]['header_items'] = $header_items;
$this->functionData['globalTemplateMinimal'][$count_4a1f80b8c3cca8df3046de6666651ea8]['items'] = $items;
$this->functionData['globalTemplateMinimal'][$count_4a1f80b8c3cca8df3046de6666651ea8]['footer_items'] = $footer_items;
$this->functionData['globalTemplateMinimal'][$count_4a1f80b8c3cca8df3046de6666651ea8]['stats'] = $stats;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- inboxList --*/
function inboxList($topics) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['inboxList'] ) )
{
$count_bdfe82c34547055343f6000a9ebc6af8 = is_array($this->functionData['inboxList']) ? count($this->functionData['inboxList']) : 0;
$this->functionData['inboxList'][$count_bdfe82c34547055343f6000a9ebc6af8]['topics'] = $topics;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- inlineUploaderComplete --*/
function inlineUploaderComplete($json) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeMoreDialogue --*/
function likeMoreDialogue($data, $relId, $cache) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['likeMoreDialogue'] ) )
{
$count_55bb7f4349971566696b9e7f43d9d5d9 = is_array($this->functionData['likeMoreDialogue']) ? count($this->functionData['likeMoreDialogue']) : 0;
$this->functionData['likeMoreDialogue'][$count_55bb7f4349971566696b9e7f43d9d5d9]['data'] = $data;
$this->functionData['likeMoreDialogue'][$count_55bb7f4349971566696b9e7f43d9d5d9]['relId'] = $relId;
$this->functionData['likeMoreDialogue'][$count_55bb7f4349971566696b9e7f43d9d5d9]['cache'] = $cache;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeSetDialogue --*/
function likeSetDialogue($app, $area, $relid, $data) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeSummary --*/
function likeSummary($data, $relId, $opts) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeSummaryContents --*/
function likeSummaryContents($data, $relId, $opts=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['likeSummaryContents'] ) )
{
$count_c5d92a2e72c9f3fd80bd341afa513a59 = is_array($this->functionData['likeSummaryContents']) ? count($this->functionData['likeSummaryContents']) : 0;
$this->functionData['likeSummaryContents'][$count_c5d92a2e72c9f3fd80bd341afa513a59]['data'] = $data;
$this->functionData['likeSummaryContents'][$count_c5d92a2e72c9f3fd80bd341afa513a59]['relId'] = $relId;
$this->functionData['likeSummaryContents'][$count_c5d92a2e72c9f3fd80bd341afa513a59]['opts'] = $opts;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- notificationsList --*/
function notificationsList($notifications) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['notificationsList'] ) )
{
$count_87e1601ec7ae132a1649f00737d44f27 = is_array($this->functionData['notificationsList']) ? count($this->functionData['notificationsList']) : 0;
$this->functionData['notificationsList'][$count_87e1601ec7ae132a1649f00737d44f27]['notifications'] = $notifications;
}
$IPBHTML .= "<template>popoverNotifications</template>
<notifications>
	".$this->__f__a88071b49fb33916a8d5cfac21c88a75($notifications)."</notifications>";
return $IPBHTML;
}


function __f__a88071b49fb33916a8d5cfac21c88a75($notifications)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $notifications as $notification )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<notification>
			<id>{$notification['notify_id']}</id>
			<url><![CDATA[{$notification['notify_url']}]]></url>
			<icon><![CDATA[{$notification['member']['pp_thumb_photo']}]]></icon>
			<text><![CDATA[{$notification['notify_title']}]]></text>
		</notification>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- privacyPolicy --*/
function privacyPolicy($title, $text) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- questionAndAnswer --*/
function questionAndAnswer($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['questionAndAnswer'] ) )
{
$count_eeaaa8c950758b7b382857e90382b4ef = is_array($this->functionData['questionAndAnswer']) ? count($this->functionData['questionAndAnswer']) : 0;
$this->functionData['questionAndAnswer'][$count_eeaaa8c950758b7b382857e90382b4ef]['data'] = $data;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- quickNavigationOffline --*/
function quickNavigationOffline($message) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- quickNavigationPanel --*/
function quickNavigationPanel($data=array(), $currentApp='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['quickNavigationPanel'] ) )
{
$count_bb5949a0de312ab365198c3df1722f41 = is_array($this->functionData['quickNavigationPanel']) ? count($this->functionData['quickNavigationPanel']) : 0;
$this->functionData['quickNavigationPanel'][$count_bb5949a0de312ab365198c3df1722f41]['data'] = $data;
$this->functionData['quickNavigationPanel'][$count_bb5949a0de312ab365198c3df1722f41]['currentApp'] = $currentApp;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- quickNavigationWrapper --*/
function quickNavigationWrapper($tabs=array(), $data=array(), $currentApp='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['quickNavigationWrapper'] ) )
{
$count_4741c726b550800d2981ebd01dfa048a = is_array($this->functionData['quickNavigationWrapper']) ? count($this->functionData['quickNavigationWrapper']) : 0;
$this->functionData['quickNavigationWrapper'][$count_4741c726b550800d2981ebd01dfa048a]['tabs'] = $tabs;
$this->functionData['quickNavigationWrapper'][$count_4741c726b550800d2981ebd01dfa048a]['data'] = $data;
$this->functionData['quickNavigationWrapper'][$count_4741c726b550800d2981ebd01dfa048a]['currentApp'] = $currentApp;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- redirectTemplate --*/
function redirectTemplate($documentHeadItems, $css, $jsLoaderItems, $text="",$url="", $full=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['redirectTemplate'] ) )
{
$count_1d8478bf6795695c610546459a58f7af = is_array($this->functionData['redirectTemplate']) ? count($this->functionData['redirectTemplate']) : 0;
$this->functionData['redirectTemplate'][$count_1d8478bf6795695c610546459a58f7af]['documentHeadItems'] = $documentHeadItems;
$this->functionData['redirectTemplate'][$count_1d8478bf6795695c610546459a58f7af]['css'] = $css;
$this->functionData['redirectTemplate'][$count_1d8478bf6795695c610546459a58f7af]['jsLoaderItems'] = $jsLoaderItems;
$this->functionData['redirectTemplate'][$count_1d8478bf6795695c610546459a58f7af]['text'] = $text;
$this->functionData['redirectTemplate'][$count_1d8478bf6795695c610546459a58f7af]['url'] = $url;
$this->functionData['redirectTemplate'][$count_1d8478bf6795695c610546459a58f7af]['full'] = $full;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- repButtons --*/
function repButtons($member, $data=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['repButtons'] ) )
{
$count_13530034eaab611754789dc47e2536e3 = is_array($this->functionData['repButtons']) ? count($this->functionData['repButtons']) : 0;
$this->functionData['repButtons'][$count_13530034eaab611754789dc47e2536e3]['member'] = $member;
$this->functionData['repButtons'][$count_13530034eaab611754789dc47e2536e3]['data'] = $data;
}
$IPBHTML .= "" . ((!( $this->settings['reputation_protected_groups'] && in_array( $member['member_group_id'], explode( ',', $this->settings['reputation_protected_groups'] ) ) ) and $this->memberData['member_id']) ? ("" . (($this->settings['reputation_point_types'] == 'like') ? ("" . ((IPSMember::canGiveRep( $data, $member ) !== false) ? ("" . ((IPSMember::canRepUp( $data, $member ) !== false) ? ("
				<likeURL><![CDATA[{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}]]></likeURL>
			") : ("")) . "") : ("")) . "") : ("" . ((IPSMember::canGiveRep( $data, $member ) !== false) ? ("
			<repupURL><![CDATA[{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}]]></repupURL>
		") : ("")) . "
		" . ((IPSMember::canRepDown( $data, $member ) !== false) ? ("
			<repDownURL><![CDATA[{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=-1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}]]></repDownURL>
		") : ("")) . "")) . "") : ("")) . "";
return $IPBHTML;
}

/* -- repMoreDialogue --*/
function repMoreDialogue($data, $relId) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- reputationPopup --*/
function reputationPopup($reps) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- socialSharePostStrip --*/
function socialSharePostStrip($id=null) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['socialSharePostStrip'] ) )
{
$count_d55f7e276b2414608d00aaf9b0450a34 = is_array($this->functionData['socialSharePostStrip']) ? count($this->functionData['socialSharePostStrip']) : 0;
$this->functionData['socialSharePostStrip'][$count_d55f7e276b2414608d00aaf9b0450a34]['id'] = $id;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- tagCloud --*/
function tagCloud($tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagCloud'] ) )
{
$count_a30b1f23cf8c1cc346199acd2999ea3d = is_array($this->functionData['tagCloud']) ? count($this->functionData['tagCloud']) : 0;
$this->functionData['tagCloud'][$count_a30b1f23cf8c1cc346199acd2999ea3d]['tags'] = $tags;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- tagEntry --*/
function tagEntry($tag, $noClass=false, $app='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagEntry'] ) )
{
$count_b6062376cd9cb37b4991f871ff50f94f = is_array($this->functionData['tagEntry']) ? count($this->functionData['tagEntry']) : 0;
$this->functionData['tagEntry'][$count_b6062376cd9cb37b4991f871ff50f94f]['tag'] = $tag;
$this->functionData['tagEntry'][$count_b6062376cd9cb37b4991f871ff50f94f]['noClass'] = $noClass;
$this->functionData['tagEntry'][$count_b6062376cd9cb37b4991f871ff50f94f]['app'] = $app;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- tagPrefix --*/
function tagPrefix($tag, $app='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagPrefix'] ) )
{
$count_4cfc81f2d4e01fae9800851288917cc3 = is_array($this->functionData['tagPrefix']) ? count($this->functionData['tagPrefix']) : 0;
$this->functionData['tagPrefix'][$count_4cfc81f2d4e01fae9800851288917cc3]['tag'] = $tag;
$this->functionData['tagPrefix'][$count_4cfc81f2d4e01fae9800851288917cc3]['app'] = $app;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- tagsAsPopUp --*/
function tagsAsPopUp($tags) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- tagTextEntryBox --*/
function tagTextEntryBox($tags, $options, $where) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagTextEntryBox'] ) )
{
$count_a3b8a23d92f29df9e2135ca10659015f = is_array($this->functionData['tagTextEntryBox']) ? count($this->functionData['tagTextEntryBox']) : 0;
$this->functionData['tagTextEntryBox'][$count_a3b8a23d92f29df9e2135ca10659015f]['tags'] = $tags;
$this->functionData['tagTextEntryBox'][$count_a3b8a23d92f29df9e2135ca10659015f]['options'] = $options;
$this->functionData['tagTextEntryBox'][$count_a3b8a23d92f29df9e2135ca10659015f]['where'] = $where;
}
$IPBHTML .= "<tagSystemIsEnabled>{$options['isEnabled']}</tagSystemIsEnabled>
<tagSystemIsOpen>{$options['isOpenSystem']}</tagSystemIsOpen>
<prefixesEnabled>{$options['prefixesEnabled']}</prefixesEnabled>
<predefinedTags>
</predefinedTags>";
return $IPBHTML;
}

/* -- twitterDone --*/
function twitterDone($user) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- twitterPop --*/
function twitterPop($user) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>