<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Tue, 28 Jan 2014 06:36:01 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_modcp_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['deletedPosts'] = array('post_data','disablelightbox','hasPosts');
$this->_funcHooks['deletedTopics'] = array('hastopics');
$this->_funcHooks['editUserForm'] = array('editusercfielddesc','custom_fields','displaynamehistory','modPreview','postingRestricted','suspended','hasRestrictions','groupCanStatus','editusercfields');
$this->_funcHooks['latestWarnLogs'] = array('warningloop','haswarnings');
$this->_funcHooks['membersList'] = array('weAreSupmod','memberwarn','sendpm','blog','gallery','norep','posrep','negrep','repson','isnotbanned','isnotbanned2','members','showmembers');
$this->_funcHooks['membersModIPForm'] = array('modIpIe');
$this->_funcHooks['membersModIPFormMembers'] = array('ipMembers','modIPMembers');
$this->_funcHooks['membersModIPFormPosts'] = array('ipPosts','modFindMemberPosts');
$this->_funcHooks['modAnnounceForm'] = array('buttonlang','announceMessage','buttonlang');
$this->_funcHooks['modAnnouncements'] = array('announce_forums','notactive','notactive','announceHasForums','announceForum','announcements','hasAnnouncements');
$this->_funcHooks['modcpMessage'] = array('hasMessage');
$this->_funcHooks['modCPpost'] = array('reputation','noRep','posRep','negRep','repIgnored','postMid','postMember','postAdmin','postIp','postIsHardDeleted','canSoftDelete','canHardDelete','hasDeletedReasonRow','hasDeletedReason','showReason','postDeletedReason','isDeleted','canEdit','approveUnapprove','approvePost','canDelete','reportedPostData','isUnapproved','postEditByReason','postEditBy','reportedPostData');
$this->_funcHooks['modCPtopic'] = array('haslastpage','pages','isLink','isLinkEnd','multipages','hasStarterId','isntLink','hasDeletedReason','showReason','topicDeletedReason','replylang','isntLink3','tidRestoreLink','canHardDeleteLinkFromDb','topicIsHardDeleted','tidRestore','canHardDeleteFromDb','isntLink4','canSoftDelete','canHardDelete','topics');
$this->_funcHooks['overview'] = array('canEditMember');
$this->_funcHooks['portalPage'] = array('tabs','accessRC');
$this->_funcHooks['subTabLoop'] = array('subTabs','isMainTab','findTab');
$this->_funcHooks['unapprovedPosts'] = array('post_data','disablelightbox','hasPosts');
$this->_funcHooks['unapprovedTopics'] = array('hastopics');


}

/* -- deletedPosts --*/
function deletedPosts($posts, $other_data=array(), $pagelinks='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['deletedPosts'] ) )
{
$count_2fb9bc136be4bc1662f6401734eac30d = is_array($this->functionData['deletedPosts']) ? count($this->functionData['deletedPosts']) : 0;
$this->functionData['deletedPosts'][$count_2fb9bc136be4bc1662f6401734eac30d]['posts'] = $posts;
$this->functionData['deletedPosts'][$count_2fb9bc136be4bc1662f6401734eac30d]['other_data'] = $other_data;
$this->functionData['deletedPosts'][$count_2fb9bc136be4bc1662f6401734eac30d]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- deletedTopics --*/
function deletedTopics($topics, $sdelete=array(), $pagelinks='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['deletedTopics'] ) )
{
$count_f070a6bda9574a71be0d4b2d333db568 = is_array($this->functionData['deletedTopics']) ? count($this->functionData['deletedTopics']) : 0;
$this->functionData['deletedTopics'][$count_f070a6bda9574a71be0d4b2d333db568]['topics'] = $topics;
$this->functionData['deletedTopics'][$count_f070a6bda9574a71be0d4b2d333db568]['sdelete'] = $sdelete;
$this->functionData['deletedTopics'][$count_f070a6bda9574a71be0d4b2d333db568]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- editUserForm --*/
function editUserForm($profile, $custom_fields=null) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['editUserForm'] ) )
{
$count_f84643428dd90f2f279720c36c95ab6e = is_array($this->functionData['editUserForm']) ? count($this->functionData['editUserForm']) : 0;
$this->functionData['editUserForm'][$count_f84643428dd90f2f279720c36c95ab6e]['profile'] = $profile;
$this->functionData['editUserForm'][$count_f84643428dd90f2f279720c36c95ab6e]['custom_fields'] = $custom_fields;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- inlineModIPMessage --*/
function inlineModIPMessage($msg='') {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- latestWarnLogs --*/
function latestWarnLogs($warnings, $pagelinks) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['latestWarnLogs'] ) )
{
$count_1ba11904ddf9fbfc1bd74149ab0a7514 = is_array($this->functionData['latestWarnLogs']) ? count($this->functionData['latestWarnLogs']) : 0;
$this->functionData['latestWarnLogs'][$count_1ba11904ddf9fbfc1bd74149ab0a7514]['warnings'] = $warnings;
$this->functionData['latestWarnLogs'][$count_1ba11904ddf9fbfc1bd74149ab0a7514]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberLookup --*/
function memberLookup() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersList --*/
function membersList($type, $members, $pagelinks='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersList'] ) )
{
$count_8a7cd7be9798c12698b8cbcf098982dc = is_array($this->functionData['membersList']) ? count($this->functionData['membersList']) : 0;
$this->functionData['membersList'][$count_8a7cd7be9798c12698b8cbcf098982dc]['type'] = $type;
$this->functionData['membersList'][$count_8a7cd7be9798c12698b8cbcf098982dc]['members'] = $members;
$this->functionData['membersList'][$count_8a7cd7be9798c12698b8cbcf098982dc]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersModIPForm --*/
function membersModIPForm($ip="", $inlineMsg='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersModIPForm'] ) )
{
$count_42be0c093828e13be18be7c75c6c6a42 = is_array($this->functionData['membersModIPForm']) ? count($this->functionData['membersModIPForm']) : 0;
$this->functionData['membersModIPForm'][$count_42be0c093828e13be18be7c75c6c6a42]['ip'] = $ip;
$this->functionData['membersModIPForm'][$count_42be0c093828e13be18be7c75c6c6a42]['inlineMsg'] = $inlineMsg;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersModIPFormMembers --*/
function membersModIPFormMembers($pages="",$members) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersModIPFormMembers'] ) )
{
$count_35ac13dcc3ce5e4d4d427df4b6f0441c = is_array($this->functionData['membersModIPFormMembers']) ? count($this->functionData['membersModIPFormMembers']) : 0;
$this->functionData['membersModIPFormMembers'][$count_35ac13dcc3ce5e4d4d427df4b6f0441c]['pages'] = $pages;
$this->functionData['membersModIPFormMembers'][$count_35ac13dcc3ce5e4d4d427df4b6f0441c]['members'] = $members;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersModIPFormPosts --*/
function membersModIPFormPosts($count=0, $pageLinks='', $results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersModIPFormPosts'] ) )
{
$count_dc3d353d2b3fb676be5312d9cf1eef48 = is_array($this->functionData['membersModIPFormPosts']) ? count($this->functionData['membersModIPFormPosts']) : 0;
$this->functionData['membersModIPFormPosts'][$count_dc3d353d2b3fb676be5312d9cf1eef48]['count'] = $count;
$this->functionData['membersModIPFormPosts'][$count_dc3d353d2b3fb676be5312d9cf1eef48]['pageLinks'] = $pageLinks;
$this->functionData['membersModIPFormPosts'][$count_dc3d353d2b3fb676be5312d9cf1eef48]['results'] = $results;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modAnnounceForm --*/
function modAnnounceForm($announce,$forum_html,$type,$editor_html,$msg="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modAnnounceForm'] ) )
{
$count_1eb8a694db4a5481f0af7fc8b2894e57 = is_array($this->functionData['modAnnounceForm']) ? count($this->functionData['modAnnounceForm']) : 0;
$this->functionData['modAnnounceForm'][$count_1eb8a694db4a5481f0af7fc8b2894e57]['announce'] = $announce;
$this->functionData['modAnnounceForm'][$count_1eb8a694db4a5481f0af7fc8b2894e57]['forum_html'] = $forum_html;
$this->functionData['modAnnounceForm'][$count_1eb8a694db4a5481f0af7fc8b2894e57]['type'] = $type;
$this->functionData['modAnnounceForm'][$count_1eb8a694db4a5481f0af7fc8b2894e57]['editor_html'] = $editor_html;
$this->functionData['modAnnounceForm'][$count_1eb8a694db4a5481f0af7fc8b2894e57]['msg'] = $msg;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modAnnouncements --*/
function modAnnouncements($announcements) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modAnnouncements'] ) )
{
$count_cfa8619ed5da2c23a8a31de78fd52fdf = is_array($this->functionData['modAnnouncements']) ? count($this->functionData['modAnnouncements']) : 0;
$this->functionData['modAnnouncements'][$count_cfa8619ed5da2c23a8a31de78fd52fdf]['announcements'] = $announcements;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modcpMessage --*/
function modcpMessage($message='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modcpMessage'] ) )
{
$count_eb21c9d932bcf60fe64f42be8a86acda = is_array($this->functionData['modcpMessage']) ? count($this->functionData['modcpMessage']) : 0;
$this->functionData['modcpMessage'][$count_eb21c9d932bcf60fe64f42be8a86acda]['message'] = $message;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- modCPpost --*/
function modCPpost($post, $displayData, $topic, $type) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modCPpost'] ) )
{
$count_4d56146438137c76e0a0fb1262e34372 = is_array($this->functionData['modCPpost']) ? count($this->functionData['modCPpost']) : 0;
$this->functionData['modCPpost'][$count_4d56146438137c76e0a0fb1262e34372]['post'] = $post;
$this->functionData['modCPpost'][$count_4d56146438137c76e0a0fb1262e34372]['displayData'] = $displayData;
$this->functionData['modCPpost'][$count_4d56146438137c76e0a0fb1262e34372]['topic'] = $topic;
$this->functionData['modCPpost'][$count_4d56146438137c76e0a0fb1262e34372]['type'] = $type;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modCPtopic --*/
function modCPtopic($topics, $pagelinks, $type, $sdelete=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modCPtopic'] ) )
{
$count_6a6c39ff4f9b377c5210680c85578ca5 = is_array($this->functionData['modCPtopic']) ? count($this->functionData['modCPtopic']) : 0;
$this->functionData['modCPtopic'][$count_6a6c39ff4f9b377c5210680c85578ca5]['topics'] = $topics;
$this->functionData['modCPtopic'][$count_6a6c39ff4f9b377c5210680c85578ca5]['pagelinks'] = $pagelinks;
$this->functionData['modCPtopic'][$count_6a6c39ff4f9b377c5210680c85578ca5]['type'] = $type;
$this->functionData['modCPtopic'][$count_6a6c39ff4f9b377c5210680c85578ca5]['sdelete'] = $sdelete;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- overview --*/
function overview() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['overview'] ) )
{
$count_522cdb4a3ab002b53a9e102a02b28244 = is_array($this->functionData['overview']) ? count($this->functionData['overview']) : 0;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- portalPage --*/
function portalPage($output, $tabs=array(), $_activeNav=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['portalPage'] ) )
{
$count_b521ee13c43a2b0f1f92a507f8fd5d46 = is_array($this->functionData['portalPage']) ? count($this->functionData['portalPage']) : 0;
$this->functionData['portalPage'][$count_b521ee13c43a2b0f1f92a507f8fd5d46]['output'] = $output;
$this->functionData['portalPage'][$count_b521ee13c43a2b0f1f92a507f8fd5d46]['tabs'] = $tabs;
$this->functionData['portalPage'][$count_b521ee13c43a2b0f1f92a507f8fd5d46]['_activeNav'] = $_activeNav;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- subTabLoop --*/
function subTabLoop() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['subTabLoop'] ) )
{
$count_dcd47933bf4059acbd34daef2e6ea5ac = is_array($this->functionData['subTabLoop']) ? count($this->functionData['subTabLoop']) : 0;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- unapprovedPosts --*/
function unapprovedPosts($posts, $pagelinks) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['unapprovedPosts'] ) )
{
$count_579c6e80f9df59bd76342119d4261343 = is_array($this->functionData['unapprovedPosts']) ? count($this->functionData['unapprovedPosts']) : 0;
$this->functionData['unapprovedPosts'][$count_579c6e80f9df59bd76342119d4261343]['posts'] = $posts;
$this->functionData['unapprovedPosts'][$count_579c6e80f9df59bd76342119d4261343]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- unapprovedTopics --*/
function unapprovedTopics($topics, $pagelinks) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['unapprovedTopics'] ) )
{
$count_98673cc079326435f8423c9ee11803e5 = is_array($this->functionData['unapprovedTopics']) ? count($this->functionData['unapprovedTopics']) : 0;
$this->functionData['unapprovedTopics'][$count_98673cc079326435f8423c9ee11803e5]['topics'] = $topics;
$this->functionData['unapprovedTopics'][$count_98673cc079326435f8423c9ee11803e5]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>