<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Tue, 28 Jan 2014 06:36:01 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_calendar_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['bbCodeEvent'] = array('timeNoEnd','hasEnds','hasEndTimeAndStart','singleDayTime','hasEndTimeNoEnds');
$this->_funcHooks['boardIndexBirthdays'] = array('age','upcomingevents','calendarEventsInner','moreBirthdays','calendarEventsOuter');
$this->_funcHooks['boardIndexCalEvents'] = array('hasCalendar','upcomingevents','calendarEventsInner','calendarEventsOuter');
$this->_funcHooks['cal_date_cell'] = array('isUrl','isUrl2','datecellqueued');
$this->_funcHooks['cal_date_cell_today'] = array('isUrl','isUrl2','todayqueued');
$this->_funcHooks['cal_week_dayentry'] = array('weekdayentryqueued');
$this->_funcHooks['calendar_likeSummaryContents'] = array('count','ilike','likeexp','likeOnlyMembers');
$this->_funcHooks['calendarBirthdayList'] = array('hasAge','members','showmembers');
$this->_funcHooks['calendarEventForm'] = array('startIsAm','startIsPm','usestandardstart','endIsAm','endIsPm','usestandardend','recurDaily','recurMonthly','recurYearly','isAllDay','hasEndDate','isRecurring','rsvpset','canaskrsvp','isPublic','isPrivate','allGroups','acpaccess','hassmilies','upload_form_check');
$this->_funcHooks['calendarEventsList'] = array('disablelightbox','canstart','hasevents','showBirthdays');
$this->_funcHooks['calendarJump'] = array('calendars','gotcalendars');
$this->_funcHooks['calendarMainContent'] = array('days','canstart');
$this->_funcHooks['calendarWeekView'] = array('canstartagain');
$this->_funcHooks['calEventFollowedWrapper'] = array('results','hasResults');
$this->_funcHooks['calEventSearchResult'] = array('showCalendarContent','isFollowed','forumsDigests','singleDayTime','hasEnds','hasEndTimeAndStart','singleDayTime','hasEndTimeNoEnds');
$this->_funcHooks['event_likeSummaryContents'] = array('count','ilike','ilikeexp','likeOnlyMembers');
$this->_funcHooks['eventAttendee'] = array('deletersvp');
$this->_funcHooks['followedContentCalendars'] = array('forumsDigests','followedResults');
$this->_funcHooks['mini_cal_date_cell'] = array('isUrl');
$this->_funcHooks['mini_cal_date_cell_today'] = array('isUrl');
$this->_funcHooks['miniCalendarWrapper'] = array('minidays');
$this->_funcHooks['modEventsWrapper'] = array('event','hasevents');
$this->_funcHooks['showEvent'] = array('attendees','attendeesagain','disablelightbox','canrate','canratelink','rate1','rate1end','rate2','rate2end','rate3','rate3end','rate4','rate4end','rate5','rate5end','hasRates','jsHasRates','ratejs','timesNotRecurring','hasEnds','hasEndTime','hasEndTimeEnds','hasrsvp1','hasrsvp2','eventnotapproved','eventmember','onlineoffline','reportpost','canedit','apporunapp','canapprove','notalreadyrsvp','canrsvp','showrsvpdiv','rsvpamount','hasattendees','extrarsvp','hasrsvp3','sharelinks');
$this->_funcHooks['showEventSimple'] = array('attendees','eventnotapproved','canrate','rate1link','rate1','rate1end','rate2','rate2end','rate3','rate3end','rate4','rate4end','rate5','rate5end','hasRates','jsHasRates','ratejs','hasattendees','rsvp','canedit','apporunapp','canapprove');


}

/* -- bbCodeEvent --*/
function bbCodeEvent($event=array(), $type='', $ends='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['bbCodeEvent'] ) )
{
$count_f8d80bc3c5e61c0c79174f92b74f4baa = is_array($this->functionData['bbCodeEvent']) ? count($this->functionData['bbCodeEvent']) : 0;
$this->functionData['bbCodeEvent'][$count_f8d80bc3c5e61c0c79174f92b74f4baa]['event'] = $event;
$this->functionData['bbCodeEvent'][$count_f8d80bc3c5e61c0c79174f92b74f4baa]['type'] = $type;
$this->functionData['bbCodeEvent'][$count_f8d80bc3c5e61c0c79174f92b74f4baa]['ends'] = $ends;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- boardIndexBirthdays --*/
function boardIndexBirthdays($birthdays, $data=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['boardIndexBirthdays'] ) )
{
$count_3298bbed5b03bf08dd31a6310cfad541 = is_array($this->functionData['boardIndexBirthdays']) ? count($this->functionData['boardIndexBirthdays']) : 0;
$this->functionData['boardIndexBirthdays'][$count_3298bbed5b03bf08dd31a6310cfad541]['birthdays'] = $birthdays;
$this->functionData['boardIndexBirthdays'][$count_3298bbed5b03bf08dd31a6310cfad541]['data'] = $data;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- boardIndexCalEvents --*/
function boardIndexCalEvents($events) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['boardIndexCalEvents'] ) )
{
$count_522e13a47c0d2c6899361aae0c17ab05 = is_array($this->functionData['boardIndexCalEvents']) ? count($this->functionData['boardIndexCalEvents']) : 0;
$this->functionData['boardIndexCalEvents'][$count_522e13a47c0d2c6899361aae0c17ab05]['events'] = $events;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_blank_cell --*/
function cal_blank_cell() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_date_cell --*/
function cal_date_cell($day=array(),$events="",$cal_date_queued="",$queued=0, $js_id) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['cal_date_cell'] ) )
{
$count_48a424d394aee2ece0d7998f31c05932 = is_array($this->functionData['cal_date_cell']) ? count($this->functionData['cal_date_cell']) : 0;
$this->functionData['cal_date_cell'][$count_48a424d394aee2ece0d7998f31c05932]['day'] = $day;
$this->functionData['cal_date_cell'][$count_48a424d394aee2ece0d7998f31c05932]['events'] = $events;
$this->functionData['cal_date_cell'][$count_48a424d394aee2ece0d7998f31c05932]['cal_date_queued'] = $cal_date_queued;
$this->functionData['cal_date_cell'][$count_48a424d394aee2ece0d7998f31c05932]['queued'] = $queued;
$this->functionData['cal_date_cell'][$count_48a424d394aee2ece0d7998f31c05932]['js_id'] = $js_id;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_date_cell_today --*/
function cal_date_cell_today($day=array(),$events="",$cal_date_queued="",$queued=0, $js_id) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['cal_date_cell_today'] ) )
{
$count_d8e290eee2ddd65f93fcf1e8ff387868 = is_array($this->functionData['cal_date_cell_today']) ? count($this->functionData['cal_date_cell_today']) : 0;
$this->functionData['cal_date_cell_today'][$count_d8e290eee2ddd65f93fcf1e8ff387868]['day'] = $day;
$this->functionData['cal_date_cell_today'][$count_d8e290eee2ddd65f93fcf1e8ff387868]['events'] = $events;
$this->functionData['cal_date_cell_today'][$count_d8e290eee2ddd65f93fcf1e8ff387868]['cal_date_queued'] = $cal_date_queued;
$this->functionData['cal_date_cell_today'][$count_d8e290eee2ddd65f93fcf1e8ff387868]['queued'] = $queued;
$this->functionData['cal_date_cell_today'][$count_d8e290eee2ddd65f93fcf1e8ff387868]['js_id'] = $js_id;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_day_bit --*/
function cal_day_bit($day="", $id='') {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_events_wrap --*/
function cal_events_wrap($event, $type='month') {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_events_wrap_manual --*/
function cal_events_wrap_manual($urlBits,$text="") {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_events_wrap_range --*/
function cal_events_wrap_range($event, $type='month') {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_events_wrap_recurring --*/
function cal_events_wrap_recurring($event, $type='month') {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_new_row --*/
function cal_new_row($week, $calendar) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_week_dayentry --*/
function cal_week_dayentry($wday="",$date="",$month="",$mid="",$year="",$events="",$queued=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['cal_week_dayentry'] ) )
{
$count_95c6e4e40b7b40d71376f611c26342c1 = is_array($this->functionData['cal_week_dayentry']) ? count($this->functionData['cal_week_dayentry']) : 0;
$this->functionData['cal_week_dayentry'][$count_95c6e4e40b7b40d71376f611c26342c1]['wday'] = $wday;
$this->functionData['cal_week_dayentry'][$count_95c6e4e40b7b40d71376f611c26342c1]['date'] = $date;
$this->functionData['cal_week_dayentry'][$count_95c6e4e40b7b40d71376f611c26342c1]['month'] = $month;
$this->functionData['cal_week_dayentry'][$count_95c6e4e40b7b40d71376f611c26342c1]['mid'] = $mid;
$this->functionData['cal_week_dayentry'][$count_95c6e4e40b7b40d71376f611c26342c1]['year'] = $year;
$this->functionData['cal_week_dayentry'][$count_95c6e4e40b7b40d71376f611c26342c1]['events'] = $events;
$this->functionData['cal_week_dayentry'][$count_95c6e4e40b7b40d71376f611c26342c1]['queued'] = $queued;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_week_events_wrap --*/
function cal_week_events_wrap($linkdata,$text="") {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- cal_week_monthbar --*/
function cal_week_monthbar($month="",$year="") {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendar_likeSummary --*/
function calendar_likeSummary($data, $relId, $opts) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendar_likeSummaryContents --*/
function calendar_likeSummaryContents($data, $relId, $opts=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['calendar_likeSummaryContents'] ) )
{
$count_138fd7b6e2e7fb7aba96e578b12b9847 = is_array($this->functionData['calendar_likeSummaryContents']) ? count($this->functionData['calendar_likeSummaryContents']) : 0;
$this->functionData['calendar_likeSummaryContents'][$count_138fd7b6e2e7fb7aba96e578b12b9847]['data'] = $data;
$this->functionData['calendar_likeSummaryContents'][$count_138fd7b6e2e7fb7aba96e578b12b9847]['relId'] = $relId;
$this->functionData['calendar_likeSummaryContents'][$count_138fd7b6e2e7fb7aba96e578b12b9847]['opts'] = $opts;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendar_rss_range --*/
function calendar_rss_range($event) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendar_rss_recurring --*/
function calendar_rss_recurring($event) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendar_rss_single --*/
function calendar_rss_single($event) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendarBirthdayList --*/
function calendarBirthdayList($rows) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['calendarBirthdayList'] ) )
{
$count_1f4c0c5df5b121263eeebf0b2dbf82f2 = is_array($this->functionData['calendarBirthdayList']) ? count($this->functionData['calendarBirthdayList']) : 0;
$this->functionData['calendarBirthdayList'][$count_1f4c0c5df5b121263eeebf0b2dbf82f2]['rows'] = $rows;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendarEventForm --*/
function calendarEventForm($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['calendarEventForm'] ) )
{
$count_1073df49529d078b615d06ba7fbe5a7b = is_array($this->functionData['calendarEventForm']) ? count($this->functionData['calendarEventForm']) : 0;
$this->functionData['calendarEventForm'][$count_1073df49529d078b615d06ba7fbe5a7b]['data'] = $data;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendarEventsList --*/
function calendarEventsList($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['calendarEventsList'] ) )
{
$count_459629cdf62687f83be3f3703f832ecc = is_array($this->functionData['calendarEventsList']) ? count($this->functionData['calendarEventsList']) : 0;
$this->functionData['calendarEventsList'][$count_459629cdf62687f83be3f3703f832ecc]['data'] = $data;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendarJump --*/
function calendarJump($calendars, $calendar, $chosen_date=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['calendarJump'] ) )
{
$count_97aa06084aa1350031e23f79f35dab63 = is_array($this->functionData['calendarJump']) ? count($this->functionData['calendarJump']) : 0;
$this->functionData['calendarJump'][$count_97aa06084aa1350031e23f79f35dab63]['calendars'] = $calendars;
$this->functionData['calendarJump'][$count_97aa06084aa1350031e23f79f35dab63]['calendar'] = $calendar;
$this->functionData['calendarJump'][$count_97aa06084aa1350031e23f79f35dab63]['chosen_date'] = $chosen_date;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendarMainContent --*/
function calendarMainContent($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['calendarMainContent'] ) )
{
$count_197e722881feabee11457f5d1b93cf20 = is_array($this->functionData['calendarMainContent']) ? count($this->functionData['calendarMainContent']) : 0;
$this->functionData['calendarMainContent'][$count_197e722881feabee11457f5d1b93cf20]['data'] = $data;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendarShowEvent --*/
function calendarShowEvent($events, $comments) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calendarWeekView --*/
function calendarWeekView($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['calendarWeekView'] ) )
{
$count_9786783f994b9720eb40fbbf215c4163 = is_array($this->functionData['calendarWeekView']) ? count($this->functionData['calendarWeekView']) : 0;
$this->functionData['calendarWeekView'][$count_9786783f994b9720eb40fbbf215c4163]['data'] = $data;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calEventFollowedWrapper --*/
function calEventFollowedWrapper($rows) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['calEventFollowedWrapper'] ) )
{
$count_c329c8f7c7d5f792e0c20d198fba393b = is_array($this->functionData['calEventFollowedWrapper']) ? count($this->functionData['calEventFollowedWrapper']) : 0;
$this->functionData['calEventFollowedWrapper'][$count_c329c8f7c7d5f792e0c20d198fba393b]['rows'] = $rows;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- calEventSearchResult --*/
function calEventSearchResult($r, $resultAsTitle=false, $type, $ends) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['calEventSearchResult'] ) )
{
$count_4cabf181e0c32ab856fc8889007e4d92 = is_array($this->functionData['calEventSearchResult']) ? count($this->functionData['calEventSearchResult']) : 0;
$this->functionData['calEventSearchResult'][$count_4cabf181e0c32ab856fc8889007e4d92]['r'] = $r;
$this->functionData['calEventSearchResult'][$count_4cabf181e0c32ab856fc8889007e4d92]['resultAsTitle'] = $resultAsTitle;
$this->functionData['calEventSearchResult'][$count_4cabf181e0c32ab856fc8889007e4d92]['type'] = $type;
$this->functionData['calEventSearchResult'][$count_4cabf181e0c32ab856fc8889007e4d92]['ends'] = $ends;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- event_likeSummary --*/
function event_likeSummary($data, $relId, $opts) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- event_likeSummaryContents --*/
function event_likeSummaryContents($data, $relId, $opts=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['event_likeSummaryContents'] ) )
{
$count_e7981a0373a7590d30eaee4f16a3fa69 = is_array($this->functionData['event_likeSummaryContents']) ? count($this->functionData['event_likeSummaryContents']) : 0;
$this->functionData['event_likeSummaryContents'][$count_e7981a0373a7590d30eaee4f16a3fa69]['data'] = $data;
$this->functionData['event_likeSummaryContents'][$count_e7981a0373a7590d30eaee4f16a3fa69]['relId'] = $relId;
$this->functionData['event_likeSummaryContents'][$count_e7981a0373a7590d30eaee4f16a3fa69]['opts'] = $opts;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- eventAttendee --*/
function eventAttendee($member, $event) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['eventAttendee'] ) )
{
$count_ee21f0613dffc2bd6acd94a700d9dd3a = is_array($this->functionData['eventAttendee']) ? count($this->functionData['eventAttendee']) : 0;
$this->functionData['eventAttendee'][$count_ee21f0613dffc2bd6acd94a700d9dd3a]['member'] = $member;
$this->functionData['eventAttendee'][$count_ee21f0613dffc2bd6acd94a700d9dd3a]['event'] = $event;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- eventsWrapper --*/
function eventsWrapper($events) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- followedContentCalendars --*/
function followedContentCalendars($rows) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['followedContentCalendars'] ) )
{
$count_2f7069ca077e969e1b715ac6cd9027e6 = is_array($this->functionData['followedContentCalendars']) ? count($this->functionData['followedContentCalendars']) : 0;
$this->functionData['followedContentCalendars'][$count_2f7069ca077e969e1b715ac6cd9027e6]['rows'] = $rows;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- mini_cal_blank_cell --*/
function mini_cal_blank_cell() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- mini_cal_date_cell --*/
function mini_cal_date_cell($day=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['mini_cal_date_cell'] ) )
{
$count_bdf127048013c01c6525b33867855f0f = is_array($this->functionData['mini_cal_date_cell']) ? count($this->functionData['mini_cal_date_cell']) : 0;
$this->functionData['mini_cal_date_cell'][$count_bdf127048013c01c6525b33867855f0f]['day'] = $day;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- mini_cal_date_cell_today --*/
function mini_cal_date_cell_today($day=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['mini_cal_date_cell_today'] ) )
{
$count_2e0817bc89aca8a82d5a4c33b7a8ea3e = is_array($this->functionData['mini_cal_date_cell_today']) ? count($this->functionData['mini_cal_date_cell_today']) : 0;
$this->functionData['mini_cal_date_cell_today'][$count_2e0817bc89aca8a82d5a4c33b7a8ea3e]['day'] = $day;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- mini_cal_new_row --*/
function mini_cal_new_row($week="", $calendar) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- miniCalendarWrapper --*/
function miniCalendarWrapper($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['miniCalendarWrapper'] ) )
{
$count_ec3dbba5b74e7d9891b3ab6aaad27cdc = is_array($this->functionData['miniCalendarWrapper']) ? count($this->functionData['miniCalendarWrapper']) : 0;
$this->functionData['miniCalendarWrapper'][$count_ec3dbba5b74e7d9891b3ab6aaad27cdc]['data'] = $data;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- modEventsWrapper --*/
function modEventsWrapper($events, $pages) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['modEventsWrapper'] ) )
{
$count_9c0744b5be544a58dfcbef4931eb58d9 = is_array($this->functionData['modEventsWrapper']) ? count($this->functionData['modEventsWrapper']) : 0;
$this->functionData['modEventsWrapper'][$count_9c0744b5be544a58dfcbef4931eb58d9]['events'] = $events;
$this->functionData['modEventsWrapper'][$count_9c0744b5be544a58dfcbef4931eb58d9]['pages'] = $pages;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- showEvent --*/
function showEvent($event, $member, $typeInfo, $like='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['showEvent'] ) )
{
$count_b6b74f0d597ac1d4b34bd119589eaf79 = is_array($this->functionData['showEvent']) ? count($this->functionData['showEvent']) : 0;
$this->functionData['showEvent'][$count_b6b74f0d597ac1d4b34bd119589eaf79]['event'] = $event;
$this->functionData['showEvent'][$count_b6b74f0d597ac1d4b34bd119589eaf79]['member'] = $member;
$this->functionData['showEvent'][$count_b6b74f0d597ac1d4b34bd119589eaf79]['typeInfo'] = $typeInfo;
$this->functionData['showEvent'][$count_b6b74f0d597ac1d4b34bd119589eaf79]['like'] = $like;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- showEventSimple --*/
function showEventSimple($event) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_calendar', $this->_funcHooks['showEventSimple'] ) )
{
$count_0fbb05fe860f1a96257e94bf6f85cb23 = is_array($this->functionData['showEventSimple']) ? count($this->functionData['showEventSimple']) : 0;
$this->functionData['showEventSimple'][$count_0fbb05fe860f1a96257e94bf6f85cb23]['event'] = $event;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>