<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 28 Jan 2014 06:35:24 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'all_converted_sofar' => "All ignored chat users converted",
'btn_continue' => "Continue...",
'chatlogs_refreshed' => "The chat logs have been refreshed",
'chatlogto' => " to ",
'chatlog__hasentered' => "%s has entered the room",
'chatlog__hasleft' => "%s has left the room",
'chat_enter_key' => "In order to use IP.Chat you must <a href='%s'>provide your IP.Board license key</a>.",
'chat_invalid_key' => "You have entered an invalid account key",
'chat_logs' => "Chat Logs",
'chat_logs_none' => "There were no logs found.  Try clicking the &quot;Refresh&quot; button to update your local archives.",
'chat_logs_refresh' => "Refresh Logs",
'chat_logs_sub' => "View Archived Chat Logs",
'chat_log_date' => "Date",
'chat_log_message' => "Message",
'chat_log_user' => "User",
'chat_log__bothvis' => "Both",
'chat_log__bothvisd' => "View both publicly and privately posted chat messages",
'chat_log__daterange' => " from ",
'chat_log__filter' => "Search for keyword",
'chat_log__privatevis' => "Private",
'chat_log__privatevisd' => "View only messages posted in private chats",
'chat_log__publicvis' => "Public",
'chat_log__publicvisd' => "View only publicly posted chat messages",
'chat_log__submit' => "Update",
'chat_no_chat' => "Your license does not include IP.Chat. Please contact account assistance for more information.",
'chat_title' => "IP.Chat",
'enter_siteid' => "Enter license key here...",
'ignoredusers_32upgrade' => "Convert Ignored Users",
'iuconvert_info' => "You can use this tool to convert ignored chat users following the upgrade to IP.Board 3.2.  If you ran this tool during the upgrade, or have run it since the upgrade, you do not need to run this again.",
'kicked_pre' => "Kicked user ",
'mem_form_ban_chat' => "Ban user from chat",
'mem_form_chat_settings' => "Chat Settings",
'mem_tab_chat' => "Chat",
'no_chat_account_number' => "You have not yet filled in your chat account number",
'ordered_ipchat' => "Supply your license key to unlock IP.Chat ",
'private_pre' => "[PRIVATE CHAT with %s] ",
're_runtool' => "Convert",
'tools_32upgrade' => "[IP.Board 3.2 Upgrade Tools]",
'upto_converted_sofar' => "Up to %s ignored chat users converted so far...",
 ); 
