<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 28 Jan 2014 06:35:24 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'menu__ipchat' => "Manage IP.Chat",
'menu__ipchat_logs' => "Chat Logs",
'menu__ipchat_tools' => "Chat Tools",
 ); 
